site_name: "MR-link and genome_integration"

repo_url: https://github.com/adriaan-vd-graaf/genome_integration


nav:
- Home: index.md  << ../README.md

- MR-link:
    - Running mr link: about_mr_link.md
    - Simulations of causal geno and phenotypes: simulation_for_mr_link.md

#- Genome integration library:
#    - About genome_integration: about_gi.md << guides/about_genome_integration.md
#    - variants: variants.md
#    - gene_regions: gene_regions.md
#    - association:  association.md
#    - resources: resources.md
#    - samples: samples.md
#    - causal_inference: causal_inference.md
#    - utils: utils.md
#    - simulate_mr: simulate_mr.md

theme: readthedocs